---
# tasks file for rancher
- name: Pull and run the Rancher server container
  docker: name="rancher_server" image=rancher/server restart_policy=always ports="8080:8080"

- name: Wait for the server rancher to start
  action: command docker logs {{ rancher_name }}
  register: rancher_logs
  until: rancher_logs.stdout.find("Listening on") != -1
  retries: 30
  delay: 10

- name: Print Rancher URL
  debug: msg="You can connect to the Rancher server http://{{ ansible_default_ipv4.address }}:{{ rancher_port }}"
  
